# Generated by Django 2.2 on 2020-05-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
