# Generated by Django 2.2 on 2020-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200515_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fav',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='report',
            field=models.CharField(choices=[('Invalid-content', 'Invalid-content')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
