# Generated by Django 2.2 on 2020-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200515_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.IntegerField(default=0),
        ),
    ]
