# Generated by Django 2.2 on 2020-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200515_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
