# Generated by Django 2.2 on 2020-05-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200515_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Question'),
        ),
    ]
