# Generated by Django 2.2 on 2020-05-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200517_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='ans_user',
        ),
    ]
