# Generated by Django 2.2 on 2020-05-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200517_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questioner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questioner', to='home.UserProfile'),
            preserve_default=False,
        ),
    ]
