# Generated by Django 2.2 on 2020-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_answer_questioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Questions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Questions',
            field=models.ManyToManyField(null=True, to='home.Question'),
        ),
    ]
