# Generated by Django 2.2 on 2020-05-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200519_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Questions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Question'),
        ),
    ]
