# Generated by Django 2.2 on 2020-05-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200520_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questioner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questioner', to='home.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile'),
            preserve_default=False,
        ),
    ]
