# Generated by Django 2.2 on 2020-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200520_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
