# Generated by Django 2.2 on 2020-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200527_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='_userprofile_followers_+', to='home.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='_userprofile_following_+', to='home.UserProfile'),
        ),
    ]
