# Generated by Django 2.2 on 2020-05-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='q_title',
            new_name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
