# Generated by Django 2.2 on 2020-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_notification_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Question_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
