# Generated by Django 2.2 on 2020-05-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_notification_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
