# Generated by Django 2.2 on 2020-05-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20200530_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='FavAnswers',
            field=models.ManyToManyField(null=True, related_name='FavAnswer', to='home.Answer'),
        ),
    ]
