# Generated by Django 2.2 on 2020-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_userprofile_favanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tag',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
